### DISCUSSION TITLE
Colorful username

### DISCUSSION THREAD

**Discussion by zxy19** [zxy19/user-decoration#2] [Decorations Share]
```css
.base .username-text {
  background: linear-gradient(135deg,#7117ea,#ea6060);
  background-size: 300%;
  -webkit-background-clip: text;
  color: transparent;
  animation: gradient-animation 3s infinite;
}

@keyframes gradient-animation {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}
```
