### DISCUSSION TITLE
Post sticker

### DISCUSSION THREAD

**Discussion by zxy19** [zxy19/user-decoration#3] [Decorations Share]
Change the image url to any image you like.

```css
.base .element-test[parent="Post-footer"]{
    background: url(https://s21.ax1x.com/2024/07/02/pkgyMW9.png);
    position: absolute;
    bottom: 40px;
    right: 48px;
    height: 64px;
    width: 64px;
    background-size: cover;
    opacity: 0.2;
}
.Post-footer{
position:relative;
}
```

**Comment by FoskyM** [comment]
Amiya is OK

![image](https://github.com/user-attachments/assets/06e03e6d-1ac7-4d1c-87dd-1706b52a395d)


```css
.base .element-test[parent="Post-footer"]{
    background: url(https://s21.ax1x.com/2024/08/27/pAkyutS.png);
    position: absolute;
    bottom: 16px;
    right: 42px;
    height: 100px;
    width: 100px;
    background-size: cover;
    opacity: 0.2;
    z-index: -10;
}
.Post-footer{
    position:relative;
}
```
