### DISCUSSION TITLE
Avatar border

### DISCUSSION THREAD

**Discussion by zxy19** [zxy19/user-decoration#4] [Decorations Share]
Example image from https://pngtree.com/

```css
.base .element-mask {
  position: absolute;
  border-radius: var(--size);
  background: url(https://s21.ax1x.com/2024/07/01/pkcWBgH.png);
  background-size: cover;
  background-position: center;
  left: -5%;
  top: -5%;
  bottom: -5%;
  right: -5%;
}
```

With animation of rotation:

```css
.base .element-mask {
  position: absolute;
  border-radius: var(--size);
  background: url(https://s21.ax1x.com/2024/07/01/pkcWBgH.png);
  background-size: cover;
  background-position: center;
  left: -5%;
  top: -5%;
  bottom: -5%;
  right: -5%;
  animation: b2afda43e3f5b 2s linear infinite;
}
@keyframes b2afda43e3f5b {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
```
